Add model UserList.Closed #114
omarcompany/rheda-messenger pull request #115
Opened 2020-09-09 16:26 UTC by SamohinSV

2020-09-09 17:08 UTC, RostovtsevDanila requested changes

2020-09-09 17:08 UTC, RostovtsevDanila commented on test/test_qml/test_user_list_model/test_UserList_model_files.pri
> +QT += sql
test_UserList_model_files.pri -> test_UserList_model_files.pro

2020-09-09 17:30 UTC, SamohinSV commented on test/test_qml/test_user_list_model/test_UserList_model_files.pri
> +QT += sql
Эээ а зачем ?

2020-09-09 19:01 UTC, alex13sh commented on application/src/userlistmodel.cpp
> +    beginResetModel();
а почему Reset? Здесь нужно `beginInsertRows(QModelIndex(), m_UserList.size(), m_UserList.size()+userList.size()-1);`

2020-09-10 07:07 UTC, RostovtsevDanila commented on test/test_qml/test_user_list_model/test_UserList_model_files.pri
> +QT += sql
А, я думал, это опечатка, извини)

2020-09-10 07:34 UTC, SamohinSV commented on application/src/userlistmodel.cpp
> +    beginResetModel();
Задумку понял. Но это будет работать, если из данных не будут удалятся User.  Так что если предпологается, что удаление из модели Account не будем делать, то ок реализую

2020-09-11 09:39 UTC, atatarov commented on application/src/userlistmodel.cpp
> +        m_UserList.append(user);
```suggestion
        m_userList.append(user);
```

2020-09-11 09:39 UTC, atatarov commented on application/src/userlistmodel.h
> +    int rowCount(const QModelIndex &parent) const;
```suggestion
    int rowCount(const QModelIndex &parent) const override;
```

2020-09-11 09:41 UTC, atatarov commented on test/test_qml/test_user_list_model/test_user_list_model.cpp
> +QUICK_TEST_MAIN_WITH_SETUP(test_user_list_model,TestUserListModel)
ты добавил функцию main, значит у тебя появился еще один бинарь, но на сервере ты его не прогоняешь? добавь в .travis.yml этот тест чтобы CI его тоже прогонял

2020-09-11 09:44 UTC, atatarov commented on application/src/userlistmodel.cpp
> +        m_UserList.append(user);
после префикса не пишем заглавную букву

2020-09-11 09:44 UTC, atatarov commented on application/src/userlistmodel.cpp
> +    roles[Name] =       "name";
зачем столько пробелов?

2020-09-11 09:44 UTC, atatarov commented on application/src/userlistmodel.h
> +    QList<User> m_UserList;
добавь еще одну секцию private, чтобы было удобно визуально разделять методы и поля класса

2020-09-11 09:46 UTC, atatarov commented on application/src/userlistmodel.cpp
> +void UserListModel::addUserlist(QList<User> userList)
не стал бы надеяться implicit sharing, все же лучше добавить const &

2020-09-11 09:49 UTC, atatarov commented on application/src/userlistmodel.cpp
> +     beginInsertRows(QModelIndex(), m_size, userList.size()-1);
тут явно не хватает отступов - выровняй строки

2020-09-11 09:51 UTC, atatarov commented on test/test_qml/test_user_list_model/tst_user_list_model.qml
> +        TestListModel.add()
выровняй строчки!

2020-09-11 09:56 UTC, atatarov commented on application/src/userlistmodel.cpp
> +    int m_size = m_UserList.size();
```suggestion
    int size = m_UserList.size();
```
префиксы указываются только полям класса, чтобы их отличать от временных переменных

2020-09-11 09:56 UTC, atatarov commented on application/src/userlistmodel.cpp
> +     for (int i=m_size; i<=userList.size()-1; i++) {
```suggestion
     for (int i = size; i <= userList.size() - 1; i++) {
```
code-style

2020-09-11 09:57 UTC, atatarov commented on application/src/userlistmodel.cpp
> +    if (m_size != userList.size()) {
в чем смысл этой проверки?

2020-09-11 09:57 UTC, atatarov commented on application/src/userlistmodel.cpp
> +     for (int i=m_size; i<=userList.size()-1; i++) {
В чем суть такого цикла?

2020-09-11 10:03 UTC, atatarov commented on application/src/userlistmodel.h
> +    void clear();
зачем тебе вообще этот метод если он не используется?

2020-09-11 10:04 UTC, SamohinSV commented on application/src/userlistmodel.h
> +    void clear();
сначала использовал, щас нет удалить ?

2020-09-11 10:06 UTC, atatarov commented on test/test_qml/test_user_list_model/test_user_list_model.pro
> +DISTFILES += \
```suggestion
DISTFILES += *.qml
```

2020-09-11 10:08 UTC, atatarov commented on application/src/userlistmodel.h
> +    void clear();
тут вопрос, как работает сервер. Сервер знает какие контакты уже не надо запрашивать? у тебя есть синхронизация с этим списком? Или он просто присылает все что есть? Если присылыает все что есть, то лучше использовать clear()

2020-09-11 10:13 UTC, SamohinSV commented on application/src/userlistmodel.cpp
> +     for (int i=m_size; i<=userList.size()-1; i++) {
Добавляет только новых user

2020-09-11 10:14 UTC, SamohinSV commented on application/src/userlistmodel.cpp
> +    if (m_size != userList.size()) {
Проверяет произошли ли какие изменения , ну а также не допускает когда  userList.size() = 0 так как цикл не переварит это

2020-09-11 10:18 UTC, SamohinSV commented on application/src/userlistmodel.h
> +    void clear();
Сервер присылает все что есть, но  в addUserList организованно так что в модель добавляется только новые

2020-09-11 11:43 UTC, alex13sh commented on application/src/userlistmodel.cpp
> +     for (int i=m_size; i<=userList.size()-1; i++) {
Мы ведь добавляем весь список в конец, который передаётся в аргумент функции.

2020-09-11 11:45 UTC, alex13sh commented on application/src/userlistmodel.cpp
> +        }
Мы ведь добавляем весь список в конец, который передаётся в аргумент функции. То есть есть достаточно так:
```suggestion
        m_userList.append(userList);
```

2020-09-13 14:22 UTC, alex13sh approved these changes

2020-09-17 06:53 UTC, atatarov commented
Поправь название коммита

2020-09-17 07:10 UTC, atatarov commented on test/test_qml/test_user_list_model/tst_user_list_model.qml
> +        function test_roles() {
Продублировал названия функции теста, из лога не понятно что тестирует эта функция. И тестирует ли вообще

2020-09-17 07:14 UTC, atatarov commented on test/test_qml/test_user_list_model/test_user_list_model.h
> +    QList<User> m_testUserListModel2;
Даже не смотря на то что это тест, не давай такие гибридные название, никаких цифр не должно быть в имени

2020-09-17 07:14 UTC, atatarov commented on test/test_qml/test_user_list_model/test_user_list_model.h
> +    QList<User> m_testUserListModel2;
зачем тебе вообще нужны эти два поля, ты же их используешь один раз?

2020-09-17 07:15 UTC, atatarov commented on application/src/userlistmodel.cpp
> +    beginInsertRows(QModelIndex(),m_userList.size(),m_userList.size()+userList.size()-1);
```suggestion
    beginInsertRows(QModelIndex(), m_userList.size(), m_userList.size()+userList.size()-1);
```
code-style
Однако я не понимаю, в чем суть и необходимость этого метода?

2020-09-17 07:20 UTC, SamohinSV commented on application/src/userlistmodel.cpp
> +    beginInsertRows(QModelIndex(),m_userList.size(),m_userList.size()+userList.size()-1);
Если с сервера пришло новые контакты,чтобы всю модель не обновлять просто добавляются снизу

2020-09-17 07:22 UTC, atatarov commented on application/src/userlistmodel.cpp
> +    beginInsertRows(QModelIndex(),m_userList.size(),m_userList.size()+userList.size()-1);
а такое бывает? сервер умеет это?

2020-09-17 10:03 UTC, atatarov approved these changes

2020-09-17 15:54 UTC, RostovtsevDanila approved these changes

2020-09-17 16:34 UTC, merged