Add contact list in UI. Closed #103
omarcompany/rheda-messenger pull request #119
Opened 2020-10-27 14:45 UTC by SamohinSV

2020-10-27 18:53 UTC, atatarov commented on application/qml/desktop/HomePage.qml
> +        y:86
плохая идея использовать абсолютное позиционирование здесь

2020-10-28 15:18 UTC, SamohinSV commented on application/qml/desktop/HomePage.qml
> +        y:86
это пока такая привязка, как  сделаю все части согласно макету, то нормально сделаю, так 86 положение согласно макету

2020-11-07 12:06 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +                text: model.name[0]
```suggestion
                text: model.name
```

2020-11-07 12:11 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +        Rectangle {
Rectangle + Text повторяются два раза и есть похожие вещи, можно сделать один компонент и не дублировать код

2020-11-07 12:13 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +    height: 78
эта высота должна складывать из суммы содержимого

2020-11-07 12:15 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +                color: '#C0C0C0'
все эти цвета не должны быть хардкорными. Пока нет палитры, можно сделать хотябы так в main.qml добавить
QtObjcet {
id: constants
readonly property greenColor: '#C0C0C0'
}
color: constants.greenColor

2020-11-07 12:22 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +Rectangle {
Сам компонент можно назвать ContactBackgroundItem, и вынести всю часть касающуюся его реализации -  градиент, mouseArea, Rectangle. И уже в этом файле его использовать
```
ContactBackgroundItem {
Row {
ContactItem { radius: 100 }
ContactItem {}
}
}
```

2020-11-07 12:24 UTC, atatarov commented on application/qml/desktop/ListContact.qml
> +        delegate: ContactDelegate {
```suggestion
        delegate: ContactDelegate {}
```

2020-11-07 12:26 UTC, atatarov commented on application/qml/desktop/HomePage.qml
> +    Rectangle {
почему убрал из header? В чем была причина? 
https://doc.qt.io/qt-5/qml-qtquick-controls2-page.html

2020-11-07 12:33 UTC, atatarov commented on application/qml/desktop/main.qml
> +
не нужна пустая строка

2020-11-08 08:21 UTC, SamohinSV commented on application/qml/desktop/HomePage.qml
> +    Rectangle {
По тому что в макете такого нет и через header только мешалось, всё равно это код будет удалятся на последующих этапах разработки

2020-11-08 08:25 UTC, SamohinSV commented on application/qml/desktop/ContactDelegate.qml
> +        Rectangle {
По мне так это лишнее, схожесть не большое на данном этапе и выделать в оддельный компанент смысла не вижу

2020-11-08 08:31 UTC, SamohinSV commented on application/qml/desktop/ContactDelegate.qml
> +    height: 78
Из суммы содержимого не получится такая высота

2020-11-08 09:42 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +        Rectangle {
нормальная сложность и выделить в отдельный компонент вполне можно

2020-11-08 09:44 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +    height: 78
если тебе нужно добавить отступы, просто прибавь их к высоте содержимого. Сейчас это мега хардкод, и это очень плохо. Раз уж цифрами все ставится, хотябы минимально делай гибкость компоненту

2020-11-08 09:44 UTC, atatarov commented on application/qml/desktop/HomePage.qml
> +    Rectangle {
тогда убери вообще надпись

2020-11-08 09:46 UTC, atatarov requested changes

2020-11-08 09:46 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +        Rectangle {
настаиваю

2020-11-08 09:49 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +        x:10
зачем абсолютное позиционирование здесь? это плохой тон

2020-11-08 09:52 UTC, atatarov commented on application/qml/desktop/HomePage.qml
> +        y:86
в макете не идеально расставлены цифры для позиционирование, не стоит их брать за основу. Это папье-маше. С таким методом масштабироваться ничего не будет. Надо просто делать в пределах разумного, без хардкода

2020-11-08 09:54 UTC, atatarov commented on application/qml/desktop/ListContact.qml
> +import QtQuick 2.0
ListContact ---> ContactList

2020-11-08 09:54 UTC, atatarov commented on application/qml/desktop/ListContact.qml
> +Rectangle {
это для чего

2020-11-08 09:59 UTC, atatarov commented on application/qml/desktop/ListContact.qml
> +Rectangle {
Не должно быть у него никакого бэкраунда, у ListVIew он состоит из делегатов и хедера, для заднего фона места нет. Так же не имеет смысла в данном случае ListView вообще выносить в отдельный файл

2020-11-08 10:05 UTC, atatarov commented on application/src/main.cpp
> +    qmlRegisterType<UserListModel>("elevons.team", 1, 0, "UserListModel");
давай будем следовать единому стилю
уже есть пример
Q_PROPERTY(MessageModel* messageList READ messageList NOTIFY messageListChanged)
значит в твоем случае можно сделать 
Q_PROPERTY(ContactModel* contactList READ contactList NOTIFY contactListChanged)

2020-11-08 10:08 UTC, atatarov commented on application/src/modelprovider.cpp
> +UserListModel *ModelProvider::userListModel() const
переименуй UserListModel в ContactModel

2020-11-08 16:16 UTC, SamohinSV commented on application/qml/desktop/HomePage.qml
> +    Rectangle {
там еще кнопка Sign out

2020-11-08 16:17 UTC, SamohinSV commented on application/qml/desktop/HomePage.qml
> +        y:86
ок, тогда сделаю с привязками для маштабирования

2020-11-10 20:31 UTC, atatarov commented on application/qml/desktop/HomePage.qml
> +    Rectangle {
ее оставь

2020-11-11 15:55 UTC, SamohinSV commented on application/qml/desktop/ContactDelegate.qml
> +        Rectangle {
Это два разных по своему назначению контейнера, объединять их в один компонент не правильно, у них по сути будет одно одинаковое свойство font.pixelSize: 20

2020-11-11 16:09 UTC, SamohinSV commented on application/qml/desktop/ListContact.qml
> +Rectangle {
ну хз в макете есть

2020-11-11 16:49 UTC, atatarov commented on application/qml/desktop/main.qml
> +    }
пробельчик убери)

2020-11-11 16:52 UTC, atatarov commented on application/qml/desktop/HomePage.qml
> +    //Временная затычка
комментарии надо писать на английском языке

2020-11-16 09:02 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +Rectangle {
Все еще не вижу компонента ContactBackgroundItem, который должен быть задним фоном для ContactDelegate. Сейчас выглядит как каша между фоном и компонентами налепленным на нем

2020-11-16 09:05 UTC, atatarov commented
Добавь в описание коммита информацию о том что переименовал UserlistModel в ContactModel

2020-11-16 09:40 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +    height: heightDelegate.height+4
почему +4? почему нельзя просто в Row Добавить topPadding

2020-11-16 09:40 UTC, atatarov commented on application/qml/desktop/ContactItem.qml
> +       anchors.centerIn: if (ckeckCenterIn) {parent}
странное решение. если !ckeckCenterIn то будет undefined? да и впринципе не ясен смысл для чего переопределять это. horizontalAlignment решает эту задачу

2020-11-16 17:53 UTC, SamohinSV commented on application/qml/desktop/ContactItem.qml
> +       anchors.centerIn: if (ckeckCenterIn) {parent}
horizontalAlignment можно и им, но все равно мне нужно что бы в круге заглавная буква в центре находилась, а где имя указывается нет, как лучше сделать хз

2020-11-16 18:33 UTC, SamohinSV commented on application/qml/desktop/ContactDelegate.qml
> +Rectangle {
ContactBackgroundItem с этим ок сделаю, а вот с ContactItem до этого компанент с таким именим был и я что то не заметив на его место новый компанент вставил, луше наверное старый метод вернуть на место, а этот переменовать ?

2020-11-16 19:47 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +Rectangle {
а старый нужен?

2020-11-16 19:49 UTC, SamohinSV commented on application/qml/desktop/ContactDelegate.qml
> +Rectangle {
ну он не используется, но сделан как задел для регистрации что ли или что то такое

2020-11-18 17:41 UTC, atatarov commented on application/qml/desktop/ContactItem.qml
> +    property bool checkCenter: false
```suggestion
    property bool checkCenter
```
по умолчанию и так false. Однако эта переменная вообще не нужна

2020-11-18 17:41 UTC, atatarov commented on application/qml/desktop/ContactItem.qml
> +       text: qsTr(textContact)
это не переводится)
```suggestion
```

2020-11-18 17:41 UTC, atatarov commented on application/qml/desktop/ContactItem.qml
> +    Text {
```suggestion
    Label {
    id: label
```

2020-11-18 17:41 UTC, atatarov commented on application/qml/desktop/ContactItem.qml
> +    property string textContact: value
```suggestion
    property alias text: label.text
    property alias horizontalAlignment: label.horizontalAlignment
```

2020-11-18 17:41 UTC, atatarov commented on application/qml/desktop/ContactDelegate.qml
> +        id:contactItems
```suggestion
        id: row
```

2020-11-18 17:41 UTC, atatarov commented on application/qml/desktop/ContactItem.qml
> +       horizontalAlignment: checkCenter ? Text.AlignHCenter: Text.AlignLeft
используй alias, инициализируй при создании компонента. см. выше

2020-11-18 18:07 UTC, atatarov approved these changes

2020-11-18 18:15 UTC, merged